### ISSUE TITLE
Javascript error in Backend

### ISSUE THREAD

**Issue by 6ui11em** [magewirephp/magewire-requirejs#3]
Using magewire in a Luma based theme with magewire-requirejs we are getting the following error in the browser console when we are in the Magento Backend:

Failed to load resource: the server responded with a status of 404 () livewire.min.js:1
Uncaught Error: Script error for: Livewire

**Comment by wpoortman** [comment]
Hi @6ui11em,

Magewire is currently only for the frontend. I'm looking into making it compatible with the backend, but this will take some time. Are you ok with me closing this issue?

**Comment by 6ui11em** [comment]
Hi @wpoortman ,
Ok, as you considere. I just want to let you know. It seemed strange to me see a javascript error in the Backend when Magewire is currently only for the frontend.

**Comment by wpoortman** [comment]
Thanks for the reply @6ui11em, I will close the issue for now :)

**Comment by LauHypershop** [comment]
I'm also experiencing this error. I believe it's because the livewire.js file in magewirephp/magewire was moved to magewirephp/magewire/view/**frontend**, while this module is calling it from view/**base**.

This looks like it might be fixed by https://github.com/magewirephp/magewire-requirejs/pull/6
